name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  common-checks:
    name: Common Checks
    permissions:
      contents: read
      pull-requests: read
    uses: nownabe/workflows/.github/workflows/pr.yaml@95b6433077e235025af5d3d012aebf75e00354a4 # v1.0.2

  filter:
    name: Filter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    outputs:
      changes: ${{ toJSON(steps.filter.outputs) }}
    steps:
      - id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v3.0.2
        with:
          filters: |
            rust:
              - '**/*.rs'
              - Cargo.toml
              - Cargo.lock
              - rust-toolchain.toml

  check-rust:
    needs: filter
    if: ${{ fromJSON(needs.filter.outputs.changes).rust == 'true' }}
    uses: ./.github/workflows/reusable-check-rust.yaml
    permissions:
      contents: read

  status:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: always()
    needs:
      - common-checks
      - check-rust
    permissions: {}
    steps:
      - name: Check job results
        env:
          HAS_FAILURE: ${{ contains(needs.*.result, 'failure') }}
          HAS_CANCELLED: ${{ contains(needs.*.result, 'cancelled') }}
        run: |
          if [[ "$HAS_FAILURE" == "true" || "$HAS_CANCELLED" == "true" ]]; then
            echo "::error::Some jobs failed or were cancelled"
            exit 1
          fi
